### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/operating-unit#36]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_operating_unit
- [x] crm_operating_unit
- [x] operating_unit
- [x] mis_builder_operating_unit #67 
- [x] stock_operating_unit  #51
- [x] sales_team_operating_unit #47
- [x] account_voucher_operating_unit  #46

**Comment by LoisRForgeFlow** [comment]
<code>account_operating_unit</code> done. https://github.com/OCA/operating-unit/pull/45

**Comment by LoisRForgeFlow** [comment]
<code>account_operating_unit</code> done. https://github.com/OCA/operating-unit/pull/50

**Comment by LoisRForgeFlow** [comment]
<code>account_voucher_operating_unit</code> added and migrated. https://github.com/OCA/operating-unit/pull/46

**Comment by LoisRForgeFlow** [comment]
<code>sales_team_operating_unit</code> added and migrated. https://github.com/OCA/operating-unit/pull/47

**Comment by LoisRForgeFlow** [comment]
<code>stock_operating_unit</code> merged https://github.com/OCA/operating-unit/pull/51

**Comment by storm-dbojkic** [comment]
All translation files are issing? can someone add them so it can be translated on transifex?
