### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/operating-unit#509]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_operating_unit - By @hbrunn - #656
- [x] analytic_operating_unit - By @BT-aleonard - #586
- [ ] hr_expense_operating_unit - By @hbrunn - #701
- [x] operating_unit - By @huguesdk - #576
- [x] product_operating_unit - By @GiuTav - #591
- [ ] purchase_operating_unit - By @BT-aleonard - #595
- [x] sale_operating_unit - By @Borruso - #600
- [ ] sale_stock_operating_unit - By @alan196 - #614
- [ ] sales_team_operating_unit
- [ ] stock_operating_unit

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by BT-aleonard** [comment]
Hi,
Can you add the following modules to the issues list:
**analytic_operating_unit**
**account_operating_unit**
**purchase_operating_unit**
**purchase_operating_unit**

Thanks.

**Comment by BT-aleonard** [comment]
Hi again,
Can you add this PR as in process of migration as well, please?
https://github.com/OCA/operating-unit/pull/586
Thanks.

**Comment by tiagor-exo** [comment]
Hi, 

I'm in the process of migrating the following modules:
**account_operating_unit
sales_team_operating_unit
purchase_operating_unit**

**Comment by GiuTav** [comment]
product_operating_unit #591

**Comment by BT-aleonard** [comment]
purchase_operating_unit https://github.com/OCA/operating-unit/pull/595

**Comment by Borruso** [comment]
I'm migrating module `stock_operating_unit` #598

**Comment by Borruso** [comment]
I'm migrating module `hr_operating_unit` #599

**Comment by Borruso** [comment]
I'm migrating module `sale_operating_unit`: #600
Depends #596 and #592

**Comment by alan196** [comment]
I have migrated sales_team_operating_unit in PR https://github.com/OCA/operating-unit/pull/613

**Comment by alan196** [comment]
I have migrated sale_stock_operating_unit in PR https://github.com/OCA/operating-unit/pull/614

**Comment by alan196** [comment]
I have migrated purchase_stock_operating_unit in PR https://github.com/OCA/operating-unit/pull/615
